In [1]:
import numpy

def select_mating_pool_roulette(pop, fitness, num_parents):
    # Selecting the best individuals in the current generation as parents for producing the offspring of the next generation.
    parents = numpy.zeros((num_parents,1,151))
    
    
    for parent_num in range(num_parents): 
        fitness_roulette = numpy.zeros(len(fitness))
        el = 0   
        for i in range(len(fitness)):
            fitness_roulette[i] = fitness[i] + el
            el = el + fitness[i]
        print(fitness_roulette)
        random_number = numpy.random.uniform(low=0, high=fitness_roulette[-1])
        print(random_number)
        find_parent = numpy.where(numpy.logical_and(fitness_roulette>=0, fitness_roulette<=random_number))
        parents[parent_num] = pop[len(find_parent[0])]
        fitness.pop(len(find_parent[0]))
        pop.pop(len(find_parent[0]))
        print(len(find_parent[0]))
    return parents
    
chromosom1 = numpy.random.uniform(low=0, high=1, size=(151,))
chromosom2 = numpy.random.uniform(low=0, high=1, size=(151,))
chromosom3 = numpy.random.uniform(low=0, high=1, size=(151,))
chromosom4 = numpy.random.uniform(low=0, high=1, size=(151,))
chromosom5 = numpy.random.uniform(low=0, high=1, size=(151,))
chromosom6 = numpy.random.uniform(low=0, high=1, size=(151,))
chromosom7 = numpy.random.uniform(low=0, high=1, size=(151,))
populacja = [chromosom1, chromosom2, chromosom3, chromosom4, chromosom5, chromosom6, chromosom7]
num_parents = 4
fitness = [0.1, 0.2, 0.5, 0.1, 0.1, 0.8, 0.6]
select_mating_pool_roulette(populacja, fitness, num_parents)

[0.1 0.3 0.8 0.9 1.  1.8 2.4]
1.616397047392416
5
[0.1 0.3 0.8 0.9 1.  1.6]
1.1687943648960162
5
[0.1 0.3 0.8 0.9 1. ]
0.027691130376287232
0
[0.2 0.7 0.8 0.9]
0.309851008518207
1


array([[[0.16279956, 0.68957276, 0.62294294, 0.30968099, 0.42790118,
         0.25114505, 0.28281017, 0.28647463, 0.02122473, 0.6037067 ,
         0.68077403, 0.21395881, 0.32380301, 0.36627629, 0.1795259 ,
         0.33847217, 0.78548201, 0.68105856, 0.75668168, 0.85807142,
         0.29124912, 0.0407289 , 0.96039372, 0.55917859, 0.79767367,
         0.96291285, 0.43607681, 0.10526961, 0.65230046, 0.93495707,
         0.16071206, 0.13448464, 0.56448025, 0.31314377, 0.79928805,
         0.23573249, 0.14747802, 0.57464174, 0.02419593, 0.16378878,
         0.04731697, 0.72050857, 0.58105629, 0.09827555, 0.59471141,
         0.35231251, 0.0885408 , 0.14551823, 0.45539835, 0.2605581 ,
         0.00268629, 0.58352502, 0.20275291, 0.42542806, 0.34072174,
         0.34559184, 0.42144998, 0.50319223, 0.66041278, 0.99406792,
         0.4484894 , 0.04189514, 0.64424413, 0.78725839, 0.75514114,
         0.8508855 , 0.62307524, 0.87260758, 0.63071288, 0.80032507,
         0.57326931, 0.16594133, 0